name: do_you_groceries
description: "UPT final project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:

  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  html: ^0.15.4
  http: ^1.2.1
  json_annotation: ^4.8.1
  meta: ^1.11.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  rive: ^0.13.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
    - assets/base/