on:
  push:

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: update packages
        run: flutter pub get

      - name: check format
        run: flutter format --line-length 120 --set-exit-if-changed ./lib

      - name: check code
        run: flutter analyze